name: "OpenVPN Client"
version: "1.0.1"
slug: "openvpn_client"
description: "A secure way to send your data through any OpenVPN Server"
url: "https://github.com/rofra/homeassistant-openvpn-client-addon"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: system
boot: auto
host_network: true
privileged:
  - NET_ADMIN
options:
  ovpnfile: ""
  ovpnpass: ""
  username: ""
  password: ""
  customargs: ""
schema:
  ovpnfile: str
  ovpnpass: password?
  username: str?
  password: password?
  customargs: str?
map:
  - config:ro